version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - infrastructure
      - javascript

  - package-ecosystem: cargo
    directory: /contracts
    schedule:
      interval: weekly
      day: monday
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - infrastructure
      - rust
